#!/usr/bin/env python3
"""
Read many sequences in one pass, and write what came of each.

Transcribing one score is a thing you watch; transcribing a catalogue is a
thing you measure. So this reports per piece how many of its bars closed and
how many are flagged, and prints the totals -- which is the only way to tell
whether a change to the pipeline helped, since nobody is going to proof read
the result.

    python3 batch.py --repertoire         # each corps' most recent season
    python3 batch.py --sample 80          # a spread across the catalogue
    python3 batch.py 2019-circus-1 ...    # named sequences
    python3 batch.py --all                # everything listed

PDFs land in work/corpus/ and stay there, ignored by git. They are working
files: the piece records the URL it was read from, so the source is one click
away from the page that shows it.
"""
import argparse
import json
import os
import random
import sys
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from fractions import Fraction

import transcribe

HERE = os.path.dirname(os.path.abspath(__file__))
CATALOGUE = os.path.join(HERE, '..', '..', 'catalogue', 'src', 'catalogue.json')
CORPUS = os.path.join(HERE, '..', 'work', 'corpus')
PIECES = os.path.join(HERE, '..', 'src', 'pieces')

AGENT = 'snare-drummer/0.1'
PAUSE = 0.3          # between requests, because this is someone else's server


def sequences(repertoire=False):
    """Every sequence, carrying the work it belongs to.

    `repertoire` narrows it to each corps' most recent season, which is the
    reduction the app works from. Which season that is comes from the
    catalogue file rather than being worked out here: the same rule computed
    twice, once in TypeScript and once in Python, would drift, and both sides
    would go on producing a plausible library.
    """
    with open(CATALOGUE, encoding='utf-8') as f:
        data = json.load(f)
    works = [w for w in data['works'] if w.get('current')] if repertoire \
        else data['works']
    return data, [
        {**sequence, 'workId': work['id'], 'corps': work['corps'],
         'circuit': work['circuit'], 'listedAt': data['source'],
         'read': data['read'],
         **({'year': work['year']} if work.get('year') else {})}
        for work in works for sequence in work['sequences']
    ]


def fetch(entry):
    """The local copy of a sequence's PDF, downloading it if it is not there."""
    path = os.path.join(CORPUS, entry['id'] + '.pdf')
    if os.path.exists(path) and os.path.getsize(path) > 1000:
        return path
    request = urllib.request.Request(entry['url'], headers={'User-Agent': AGENT})
    try:
        with urllib.request.urlopen(request, timeout=90) as response:
            body = response.read()
    except Exception as exc:
        return exc
    with open(path, 'wb') as f:
        f.write(body)
    time.sleep(PAUSE)
    return path


def score(piece):
    """How many bars of a piece are both trustworthy and worth playing.

    The trust half mirrors what @snare-drummer/core will decide once the piece
    crosses into TypeScript -- it is not the authority, which stays there,
    only a way of seeing the run.

    A bar also has to contain a stroke. A bar of rests that fills its metre
    is verified and silent, and one score here came out as 204 bars holding
    five rests and nothing else: entirely trustworthy, and nothing to practise.
    """
    playable = 0
    for bar in piece['bars']:
        if bar['unnamedSymbols'] or bar['readFrom'] != 'notation':
            continue
        if bar['meter'] is None or not bar['events']:
            continue
        if not any(not e.get('rest') for e in bar['events']):
            continue
        played = sum(Fraction(*e['duration']) for e in bar['events'])
        if played == Fraction(bar['meter'][0] * 4, bar['meter'][1]):
            playable += 1
    return playable


MANIFEST_HEAD = '''/**
 * Every transcribed sequence, as the pipeline wrote it.
 *
 * Generated by packages/transcription/pipeline/batch.py -- edit the pipeline,
 * not this file. It exists so the pieces are ordinary typed imports rather
 * than a bundler's directory glob: the package has to compile with plain tsc,
 * and a list somebody can read is worth more than one line of cleverness.
 */
'''


def manifest(ids):
    lines = [MANIFEST_HEAD]
    for i, piece in enumerate(ids):
        lines.append(f"import piece{i} from './{piece}.json' with {{ type: 'json' }}")
    lines.append('')
    lines.append('export const RAW_PIECES: readonly unknown[] = [')
    for i in range(len(ids)):
        lines.append(f'  piece{i},')
    lines.append(']')
    lines.append('')
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('ids', nargs='*')
    parser.add_argument('--sample', type=int, help='that many, spread at random')
    parser.add_argument('--all', action='store_true')
    parser.add_argument('--repertoire', action='store_true',
                        help="each corps' most recent season")
    parser.add_argument('--seed', type=int, default=7)
    args = parser.parse_args()

    _data, entries = sequences(repertoire=args.repertoire)
    if args.repertoire or args.all:
        chosen = entries
    elif args.sample:
        random.seed(args.seed)
        chosen = random.sample(entries, min(args.sample, len(entries)))
    elif args.ids:
        by_id = {e['id']: e for e in entries}
        missing = [i for i in args.ids if i not in by_id]
        if missing:
            raise SystemExit(f"inconnu: {', '.join(missing)}")
        chosen = [by_id[i] for i in args.ids]
    else:
        parser.error('donner des ids, --sample N, --repertoire ou --all')

    os.makedirs(CORPUS, exist_ok=True)
    os.makedirs(PIECES, exist_ok=True)

    with ThreadPoolExecutor(max_workers=4) as pool:
        paths = list(pool.map(fetch, chosen))

    written, skipped, bars_total, bars_trusted = [], [], 0, 0
    for entry, path in zip(chosen, paths):
        if not isinstance(path, str):
            skipped.append((entry['id'], f'telechargement: {str(path)[:40]}'))
            continue
        try:
            piece = transcribe.transcribe(path, entry)
        except Exception as exc:
            skipped.append((entry['id'], f'{type(exc).__name__}: {str(exc)[:40]}'))
            continue
        if not piece['bars']:
            # Nothing was read at all. A piece with no bars has nothing to
            # show and nothing to flag, so it is left out and said so.
            skipped.append((entry['id'], 'aucune mesure trouvée'))
            continue
        good = score(piece)
        if good == 0:
            # A suspect bar belongs in the app: it is shown marked, beside
            # the bars around it that can be trusted. A piece where *nothing*
            # verified has no such neighbours -- there is nothing to play and
            # nothing to compare against -- so it is left out rather than
            # shipped as a score that cannot be believed anywhere.
            skipped.append((entry['id'],
                            f"0/{len(piece['bars'])} mesures jouables"))
            continue
        with open(os.path.join(PIECES, entry['id'] + '.json'), 'w',
                  encoding='utf-8') as f:
            json.dump(piece, f, ensure_ascii=False, separators=(',', ':'))
        written.append((entry['id'], good, len(piece['bars'])))
        bars_total += len(piece['bars'])
        bars_trusted += good

    kept = sorted(os.listdir(PIECES))
    ids = [name[:-5] for name in kept if name.endswith('.json')]
    with open(os.path.join(PIECES, 'index.ts'), 'w', encoding='utf-8') as f:
        f.write(manifest(ids))

    written.sort(key=lambda r: -(r[1] / r[2]))
    for piece_id, good, total in written[:10]:
        print(f"  {piece_id:<40} {good:>4}/{total:<4} mesures jouables")
    if len(written) > 10:
        print(f"  … et {len(written) - 10} autres")
    print()
    print(f"{len(written)} séquences écrites, {len(skipped)} laissées de côté")
    for piece_id, why in skipped[:8]:
        print(f"    {piece_id:<40} {why}")
    if bars_total:
        print(f"{bars_total} mesures, {bars_trusted} jouables "
              f"({100 * bars_trusted / bars_total:.1f}%)")
    print(f"{len(ids)} pièces dans src/pieces/")


if __name__ == '__main__':
    main()
