/**
 * Every transcribed sequence, as the pipeline wrote it.
 *
 * Generated by packages/transcription/pipeline/batch.py -- edit the pipeline,
 * not this file. It exists so the pieces are ordinary typed imports rather
 * than a bundler's directory glob: the package has to compile with plain tsc,
 * and a list somebody can read is worth more than one line of cleverness.
 */

import piece0 from './1999-opener-1.json' with { type: 'json' }
import piece1 from './2004-opener-segment-1.json' with { type: 'json' }
import piece2 from './2006-drum-break.json' with { type: 'json' }
import piece3 from './2009-closer-1.json' with { type: 'json' }
import piece4 from './2009-opener-segment-fall-season.json' with { type: 'json' }
import piece5 from './2009-segment-1.json' with { type: 'json' }
import piece6 from './2010-drum-feature-1.json' with { type: 'json' }
import piece7 from './2010-drum-feature-5.json' with { type: 'json' }
import piece8 from './2010-opener1.json' with { type: 'json' }
import piece9 from './2010-segment-1.json' with { type: 'json' }
import piece10 from './2011-bloo-rolls.json' with { type: 'json' }
import piece11 from './2011-closer-finals.json' with { type: 'json' }
import piece12 from './2011-movement-2-7.json' with { type: 'json' }
import piece13 from './2011-opener-23.json' with { type: 'json' }
import piece14 from './2011-opener-7.json' with { type: 'json' }
import piece15 from './2012-fall-drum-feature.json' with { type: 'json' }
import piece16 from './2012-movement-2.json' with { type: 'json' }
import piece17 from './2012-opener-1.json' with { type: 'json' }
import piece18 from './2012-opener-15.json' with { type: 'json' }
import piece19 from './2012-opener-finals-1.json' with { type: 'json' }
import piece20 from './2012-part-3-1.json' with { type: 'json' }
import piece21 from './2012-peppy-and-george-1.json' with { type: 'json' }
import piece22 from './2012-segment-1.json' with { type: 'json' }
import piece23 from './2013-feature-2.json' with { type: 'json' }
import piece24 from './2013-movement-2-12.json' with { type: 'json' }
import piece25 from './2013-opener.json' with { type: 'json' }
import piece26 from './2014-feature.json' with { type: 'json' }
import piece27 from './2014-movement-2-segment.json' with { type: 'json' }
import piece28 from './2014-opener1-1.json' with { type: 'json' }
import piece29 from './2014-sterling1-1.json' with { type: 'json' }
import piece30 from './2015-bkat-snare-solo.json' with { type: 'json' }
import piece31 from './2015-feature-5.json' with { type: 'json' }
import piece32 from './2016-feature-1.json' with { type: 'json' }
import piece33 from './2016-journey.json' with { type: 'json' }
import piece34 from './2016-lick.json' with { type: 'json' }
import piece35 from './2016-movements-1-and-2.json' with { type: 'json' }
import piece36 from './2016-snare-break-2.json' with { type: 'json' }
import piece37 from './2016-snare-feature-latest.json' with { type: 'json' }
import piece38 from './2017-closer1.json' with { type: 'json' }
import piece39 from './2017-drum-break.json' with { type: 'json' }
import piece40 from './2017-duets.json' with { type: 'json' }
import piece41 from './2017-movement-21.json' with { type: 'json' }
import piece42 from './2017-movement-3-early-season-1.json' with { type: 'json' }
import piece43 from './2017-opener-15.json' with { type: 'json' }
import piece44 from './2017-opener.json' with { type: 'json' }
import piece45 from './2018-ballad.json' with { type: 'json' }
import piece46 from './2018-carpenter.json' with { type: 'json' }
import piece47 from './2018-closer-2.json' with { type: 'json' }
import piece48 from './2018-eights-and-legatos.json' with { type: 'json' }
import piece49 from './2018-movement-2-6.json' with { type: 'json' }
import piece50 from './2018-opener-11.json' with { type: 'json' }
import piece51 from './2018-opener-fall-season.json' with { type: 'json' }
import piece52 from './2018-opener-snare-break.json' with { type: 'json' }
import piece53 from './2018-snare-break-3.json' with { type: 'json' }
import piece54 from './2018-snare-lick.json' with { type: 'json' }
import piece55 from './double-beat-1.json' with { type: 'json' }

export const RAW_PIECES: readonly unknown[] = [
  piece0,
  piece1,
  piece2,
  piece3,
  piece4,
  piece5,
  piece6,
  piece7,
  piece8,
  piece9,
  piece10,
  piece11,
  piece12,
  piece13,
  piece14,
  piece15,
  piece16,
  piece17,
  piece18,
  piece19,
  piece20,
  piece21,
  piece22,
  piece23,
  piece24,
  piece25,
  piece26,
  piece27,
  piece28,
  piece29,
  piece30,
  piece31,
  piece32,
  piece33,
  piece34,
  piece35,
  piece36,
  piece37,
  piece38,
  piece39,
  piece40,
  piece41,
  piece42,
  piece43,
  piece44,
  piece45,
  piece46,
  piece47,
  piece48,
  piece49,
  piece50,
  piece51,
  piece52,
  piece53,
  piece54,
  piece55,
]
