/**
 * Every transcribed sequence, as the pipeline wrote it.
 *
 * Generated by packages/transcription/pipeline/run/batch.py -- edit the pipeline,
 * not this file. It exists so the pieces are ordinary typed imports rather
 * than a bundler's directory glob: the package has to compile with plain tsc,
 * and a list somebody can read is worth more than one line of cleverness.
 */

import piece0 from './1993-closer.json' with { type: 'json' }
import piece1 from './1993-drum-break.json' with { type: 'json' }
import piece2 from './1993-opener.json' with { type: 'json' }
import piece3 from './2004-battery-break.json' with { type: 'json' }
import piece4 from './2004-feature.json' with { type: 'json' }
import piece5 from './2009-drum-feature-5.json' with { type: 'json' }
import piece6 from './2009-skol-vikings-audition-piece-1.json' with { type: 'json' }
import piece7 from './2010-feature-5.json' with { type: 'json' }
import piece8 from './2011-movement-1-1.json' with { type: 'json' }
import piece9 from './2011-movement-4.json' with { type: 'json' }
import piece10 from './2011-opener-22.json' with { type: 'json' }
import piece11 from './2014-opener-feature.json' with { type: 'json' }
import piece12 from './2015-feature-10.json' with { type: 'json' }
import piece13 from './2015-feature-5.json' with { type: 'json' }
import piece14 from './2016-intro-1.json' with { type: 'json' }
import piece15 from './2016-movement-3-5.json' with { type: 'json' }
import piece16 from './2016-movement-4-2.json' with { type: 'json' }
import piece17 from './2017-closer-early-season.json' with { type: 'json' }
import piece18 from './2017-excerpt-mid-season.json' with { type: 'json' }
import piece19 from './2017-movement-2-break.json' with { type: 'json' }
import piece20 from './2017-movement-2.json' with { type: 'json' }
import piece21 from './2017-opener-2.json' with { type: 'json' }
import piece22 from './2017-opener-3.json' with { type: 'json' }
import piece23 from './2017-opener-8.json' with { type: 'json' }
import piece24 from './2017-opening-feature.json' with { type: 'json' }
import piece25 from './2017-opening-snare-break.json' with { type: 'json' }
import piece26 from './2017-snare-break-5.json' with { type: 'json' }
import piece27 from './2017-snare-feature-1.json' with { type: 'json' }
import piece28 from './2018-8s.json' with { type: 'json' }
import piece29 from './2018-8th-note-rolls.json' with { type: 'json' }
import piece30 from './2018-carpenter.json' with { type: 'json' }
import piece31 from './2018-closer-1.json' with { type: 'json' }
import piece32 from './2018-closer-2.json' with { type: 'json' }
import piece33 from './2018-eights-and-legatos.json' with { type: 'json' }
import piece34 from './2018-movement-2-6.json' with { type: 'json' }
import piece35 from './2018-opener-3.json' with { type: 'json' }
import piece36 from './2018-opener-4.json' with { type: 'json' }
import piece37 from './2018-snare-break-early-season-1.json' with { type: 'json' }
import piece38 from './2018-snare-feature-1.json' with { type: 'json' }
import piece39 from './2018-snare-feature-3.json' with { type: 'json' }
import piece40 from './2018-snare-feature.json' with { type: 'json' }
import piece41 from './2018-triplet-rolls.json' with { type: 'json' }
import piece42 from './2019-ballad.json' with { type: 'json' }
import piece43 from './2019-circus-1.json' with { type: 'json' }
import piece44 from './2019-closer-5.json' with { type: 'json' }
import piece45 from './2019-closer-6.json' with { type: 'json' }
import piece46 from './2019-closer-snare-break.json' with { type: 'json' }
import piece47 from './2019-closer.json' with { type: 'json' }
import piece48 from './2019-drum-break-as-of-8-1-19.json' with { type: 'json' }
import piece49 from './2019-drum-break.json' with { type: 'json' }
import piece50 from './2019-ghost-break.json' with { type: 'json' }
import piece51 from './2019-movement-2-11.json' with { type: 'json' }
import piece52 from './2019-movement-3-1.json' with { type: 'json' }
import piece53 from './2019-movement-7.json' with { type: 'json' }
import piece54 from './2019-opener-1.json' with { type: 'json' }
import piece55 from './2019-opener-13.json' with { type: 'json' }
import piece56 from './2019-opener-4.json' with { type: 'json' }
import piece57 from './2019-opener-early-season-1.json' with { type: 'json' }
import piece58 from './2019-snare-break-early-season-1.json' with { type: 'json' }
import piece59 from './2019-snare-break.json' with { type: 'json' }
import piece60 from './come-and-get-it.json' with { type: 'json' }
import piece61 from './fragile.json' with { type: 'json' }
import piece62 from './get-the-feeling-solo.json' with { type: 'json' }
import piece63 from './get-your-freak-on.json' with { type: 'json' }
import piece64 from './know-you-like-it.json' with { type: 'json' }
import piece65 from './lets-go.json' with { type: 'json' }
import piece66 from './roots-2017-snare-feature.json' with { type: 'json' }
import piece67 from './solo.json' with { type: 'json' }
import piece68 from './start-it-up.json' with { type: 'json' }

export const RAW_PIECES: readonly unknown[] = [
  piece0,
  piece1,
  piece2,
  piece3,
  piece4,
  piece5,
  piece6,
  piece7,
  piece8,
  piece9,
  piece10,
  piece11,
  piece12,
  piece13,
  piece14,
  piece15,
  piece16,
  piece17,
  piece18,
  piece19,
  piece20,
  piece21,
  piece22,
  piece23,
  piece24,
  piece25,
  piece26,
  piece27,
  piece28,
  piece29,
  piece30,
  piece31,
  piece32,
  piece33,
  piece34,
  piece35,
  piece36,
  piece37,
  piece38,
  piece39,
  piece40,
  piece41,
  piece42,
  piece43,
  piece44,
  piece45,
  piece46,
  piece47,
  piece48,
  piece49,
  piece50,
  piece51,
  piece52,
  piece53,
  piece54,
  piece55,
  piece56,
  piece57,
  piece58,
  piece59,
  piece60,
  piece61,
  piece62,
  piece63,
  piece64,
  piece65,
  piece66,
  piece67,
  piece68,
]
